name = "Yao_work"
uuid = "d404b157-65b1-4708-ab3c-24f9f950c303"
authors = ["upapa <jhchu@hotmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
